# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'consultafornecedorcliente.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(780, 500)
        Dialog.setMinimumSize(QtCore.QSize(780, 500))
        Dialog.setMaximumSize(QtCore.QSize(780, 500))
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 80, 81, 61))
        self.groupBox.setObjectName("groupBox")
        self.radioFisica = QtWidgets.QRadioButton(self.groupBox)
        self.radioFisica.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.radioFisica.setObjectName("radioFisica")
        self.radioJuridica = QtWidgets.QRadioButton(self.groupBox)
        self.radioJuridica.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.radioJuridica.setObjectName("radioJuridica")
        self.cmpCodigo = QtWidgets.QLineEdit(Dialog)
        self.cmpCodigo.setGeometry(QtCore.QRect(20, 50, 51, 20))
        self.cmpCodigo.setObjectName("cmpCodigo")
        self.cmpCidade = QtWidgets.QLineEdit(Dialog)
        self.cmpCidade.setGeometry(QtCore.QRect(120, 100, 211, 20))
        self.cmpCidade.setObjectName("cmpCidade")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(120, 30, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 41, 16))
        self.label.setObjectName("label")
        self.label_28 = QtWidgets.QLabel(Dialog)
        self.label_28.setGeometry(QtCore.QRect(120, 80, 71, 16))
        self.label_28.setObjectName("label_28")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(490, 30, 101, 16))
        self.label_3.setObjectName("label_3")
        self.cmpNomeFantasia = QtWidgets.QLineEdit(Dialog)
        self.cmpNomeFantasia.setGeometry(QtCore.QRect(490, 50, 241, 20))
        self.cmpNomeFantasia.setObjectName("cmpNomeFantasia")
        self.cmpRazaoSocial = QtWidgets.QLineEdit(Dialog)
        self.cmpRazaoSocial.setGeometry(QtCore.QRect(120, 50, 361, 20))
        self.cmpRazaoSocial.setObjectName("cmpRazaoSocial")
        self.btnLimpar = QtWidgets.QPushButton(Dialog)
        self.btnLimpar.setGeometry(QtCore.QRect(340, 420, 75, 23))
        self.btnLimpar.setStyleSheet("QPushButton::menu-indicator {\n"
"    image: url(download.png);\n"
"    subcontrol-position: right center;\n"
"    subcontrol-origin: padding;\n"
"    left: -2px;\n"
"}")
        self.btnLimpar.setCheckable(False)
        self.btnLimpar.setAutoRepeat(False)
        self.btnLimpar.setAutoExclusive(False)
        self.btnLimpar.setAutoDefault(False)
        self.btnLimpar.setDefault(False)
        self.btnLimpar.setFlat(False)
        self.btnLimpar.setObjectName("btnLimpar")
        self.btnAbrir = QtWidgets.QPushButton(Dialog)
        self.btnAbrir.setGeometry(QtCore.QRect(250, 420, 75, 23))
        self.btnAbrir.setObjectName("btnAbrir")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(120, 200, 531, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.btnPesquisar = QtWidgets.QPushButton(Dialog)
        self.btnPesquisar.setGeometry(QtCore.QRect(350, 100, 75, 23))
        self.btnPesquisar.setObjectName("btnPesquisar")
        self.btnSair = QtWidgets.QPushButton(Dialog)
        self.btnSair.setGeometry(QtCore.QRect(430, 420, 75, 23))
        self.btnSair.setStyleSheet("QPushButton::menu-indicator {\n"
"    image: url(download.png);\n"
"    subcontrol-position: right center;\n"
"    subcontrol-origin: padding;\n"
"    left: -2px;\n"
"}")
        self.btnSair.setCheckable(False)
        self.btnSair.setAutoRepeat(False)
        self.btnSair.setAutoExclusive(False)
        self.btnSair.setAutoDefault(False)
        self.btnSair.setDefault(False)
        self.btnSair.setFlat(False)
        self.btnSair.setObjectName("btnSair")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Consulta de Fornecedor"))
        self.groupBox.setTitle(_translate("Dialog", "Pessoa:"))
        self.radioFisica.setText(_translate("Dialog", "Física"))
        self.radioJuridica.setText(_translate("Dialog", "Jurídica"))
        self.label_2.setText(_translate("Dialog", "Razão Social"))
        self.label.setText(_translate("Dialog", "Código"))
        self.label_28.setText(_translate("Dialog", "Cidade"))
        self.label_3.setText(_translate("Dialog", "Nome Fantasia"))
        self.btnLimpar.setText(_translate("Dialog", "Limpar"))
        self.btnAbrir.setText(_translate("Dialog", "Abrir"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Código"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Razão Social"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Nome Fantasia"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Tipo de Pessoa"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Cidade"))
        self.btnPesquisar.setText(_translate("Dialog", "Pesquisar"))
        self.btnSair.setText(_translate("Dialog", "Sair"))

