# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'produtoteste.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Produto(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1056, 738)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 90, 81, 16))
        self.label_4.setObjectName("label_4")
        self.cmpAltura = QtWidgets.QLineEdit(Dialog)
        self.cmpAltura.setGeometry(QtCore.QRect(380, 240, 101, 20))
        self.cmpAltura.setObjectName("cmpAltura")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(30, 340, 61, 16))
        self.label_22.setObjectName("label_22")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(270, 90, 101, 16))
        self.label_6.setObjectName("label_6")
        self.toolCodForn = QtWidgets.QToolButton(Dialog)
        self.toolCodForn.setGeometry(QtCore.QRect(90, 300, 25, 19))
        self.toolCodForn.setObjectName("toolCodForn")
        self.toolCodProd = QtWidgets.QToolButton(Dialog)
        self.toolCodProd.setGeometry(QtCore.QRect(90, 50, 25, 19))
        self.toolCodProd.setObjectName("toolCodProd")
        self.cmpDescricaoFornecedor = QtWidgets.QLineEdit(Dialog)
        self.cmpDescricaoFornecedor.setGeometry(QtCore.QRect(130, 300, 361, 20))
        self.cmpDescricaoFornecedor.setObjectName("cmpDescricaoFornecedor")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(300, 150, 91, 16))
        self.label_12.setObjectName("label_12")
        self.cmpDescricao = QtWidgets.QLineEdit(Dialog)
        self.cmpDescricao.setGeometry(QtCore.QRect(130, 50, 361, 20))
        self.cmpDescricao.setObjectName("cmpDescricao")
        self.comboUnidForn = QtWidgets.QComboBox(Dialog)
        self.comboUnidForn.setGeometry(QtCore.QRect(490, 110, 69, 22))
        self.comboUnidForn.setObjectName("comboUnidForn")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(380, 90, 81, 16))
        self.label_7.setObjectName("label_7")
        self.cmpCodAlternativo = QtWidgets.QLineEdit(Dialog)
        self.cmpCodAlternativo.setGeometry(QtCore.QRect(30, 360, 51, 20))
        self.cmpCodAlternativo.setText("")
        self.cmpCodAlternativo.setObjectName("cmpCodAlternativo")
        self.cmpDescricaoReduzida = QtWidgets.QLineEdit(Dialog)
        self.cmpDescricaoReduzida.setGeometry(QtCore.QRect(500, 50, 361, 20))
        self.cmpDescricaoReduzida.setText("")
        self.cmpDescricaoReduzida.setObjectName("cmpDescricaoReduzida")
        self.comboUnidEnt = QtWidgets.QComboBox(Dialog)
        self.comboUnidEnt.setGeometry(QtCore.QRect(30, 170, 69, 22))
        self.comboUnidEnt.setObjectName("comboUnidEnt")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(130, 280, 131, 16))
        self.label_18.setObjectName("label_18")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(30, 220, 71, 16))
        self.label_14.setObjectName("label_14")
        self.cmpDun14 = QtWidgets.QLineEdit(Dialog)
        self.cmpDun14.setGeometry(QtCore.QRect(160, 110, 101, 20))
        self.cmpDun14.setText("")
        self.cmpDun14.setObjectName("cmpDun14")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setGeometry(QtCore.QRect(160, 220, 81, 16))
        self.label_17.setObjectName("label_17")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(110, 150, 91, 16))
        self.label_10.setObjectName("label_10")
        self.cmpLargura = QtWidgets.QLineEdit(Dialog)
        self.cmpLargura.setGeometry(QtCore.QRect(270, 240, 101, 20))
        self.cmpLargura.setObjectName("cmpLargura")
        self.cmpFatorEntrada = QtWidgets.QLineEdit(Dialog)
        self.cmpFatorEntrada.setGeometry(QtCore.QRect(110, 170, 101, 20))
        self.cmpFatorEntrada.setObjectName("cmpFatorEntrada")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(570, 90, 111, 16))
        self.label_9.setObjectName("label_9")
        self.cmpCodForn = QtWidgets.QLineEdit(Dialog)
        self.cmpCodForn.setGeometry(QtCore.QRect(30, 300, 51, 21))
        self.cmpCodForn.setObjectName("cmpCodForn")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(410, 150, 71, 16))
        self.label_23.setObjectName("label_23")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(270, 220, 81, 16))
        self.label_15.setObjectName("label_15")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(130, 340, 201, 16))
        self.label_21.setObjectName("label_21")
        self.cmpDescricaoFornecedorAlternativo = QtWidgets.QLineEdit(Dialog)
        self.cmpDescricaoFornecedorAlternativo.setGeometry(QtCore.QRect(130, 360, 361, 20))
        self.cmpDescricaoFornecedorAlternativo.setText("")
        self.cmpDescricaoFornecedorAlternativo.setObjectName("cmpDescricaoFornecedorAlternativo")
        self.comboUnidVenda = QtWidgets.QComboBox(Dialog)
        self.comboUnidVenda.setGeometry(QtCore.QRect(220, 170, 69, 22))
        self.comboUnidVenda.setEditable(False)
        self.comboUnidVenda.setObjectName("comboUnidVenda")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 30, 41, 16))
        self.label.setObjectName("label")
        self.cmpCodBarras = QtWidgets.QLineEdit(Dialog)
        self.cmpCodBarras.setGeometry(QtCore.QRect(30, 110, 121, 20))
        self.cmpCodBarras.setText("")
        self.cmpCodBarras.setObjectName("cmpCodBarras")
        self.cmpNcmSh = QtWidgets.QLineEdit(Dialog)
        self.cmpNcmSh.setGeometry(QtCore.QRect(380, 110, 101, 20))
        self.cmpNcmSh.setText("")
        self.cmpNcmSh.setObjectName("cmpNcmSh")
        self.comboClassifAbc = QtWidgets.QComboBox(Dialog)
        self.comboClassifAbc.setGeometry(QtCore.QRect(410, 170, 69, 22))
        self.comboClassifAbc.setEditable(False)
        self.comboClassifAbc.setObjectName("comboClassifAbc")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(490, 90, 81, 16))
        self.label_8.setObjectName("label_8")
        self.cmpFatorFornecedor = QtWidgets.QLineEdit(Dialog)
        self.cmpFatorFornecedor.setGeometry(QtCore.QRect(570, 110, 101, 20))
        self.cmpFatorFornecedor.setObjectName("cmpFatorFornecedor")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(160, 90, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(380, 220, 81, 16))
        self.label_16.setObjectName("label_16")
        self.cmpComprimento = QtWidgets.QLineEdit(Dialog)
        self.cmpComprimento.setGeometry(QtCore.QRect(160, 240, 101, 20))
        self.cmpComprimento.setObjectName("cmpComprimento")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(30, 280, 51, 16))
        self.label_19.setObjectName("label_19")
        self.cmpCodPatrimonio = QtWidgets.QLineEdit(Dialog)
        self.cmpCodPatrimonio.setGeometry(QtCore.QRect(270, 110, 101, 20))
        self.cmpCodPatrimonio.setText("")
        self.cmpCodPatrimonio.setObjectName("cmpCodPatrimonio")
        self.pushBtnLimpar = QtWidgets.QPushButton(Dialog)
        self.pushBtnLimpar.setGeometry(QtCore.QRect(220, 410, 75, 23))
        self.pushBtnLimpar.setStyleSheet("QPushButton::menu-indicator {\n"
"    image: url(download.png);\n"
"    subcontrol-position: right center;\n"
"    subcontrol-origin: padding;\n"
"    left: -2px;\n"
"}")
        self.pushBtnLimpar.setCheckable(False)
        self.pushBtnLimpar.setAutoRepeat(False)
        self.pushBtnLimpar.setAutoExclusive(False)
        self.pushBtnLimpar.setAutoDefault(False)
        self.pushBtnLimpar.setDefault(False)
        self.pushBtnLimpar.setFlat(False)
        self.pushBtnLimpar.setObjectName("pushBtnLimpar")
        self.cmpFatorVenda = QtWidgets.QLineEdit(Dialog)
        self.cmpFatorVenda.setGeometry(QtCore.QRect(300, 170, 101, 20))
        self.cmpFatorVenda.setObjectName("cmpFatorVenda")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(220, 150, 81, 16))
        self.label_13.setObjectName("label_13")
        self.toolCodFornAlternativo = QtWidgets.QToolButton(Dialog)
        self.toolCodFornAlternativo.setGeometry(QtCore.QRect(90, 360, 25, 19))
        self.toolCodFornAlternativo.setObjectName("toolCodFornAlternativo")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(30, 150, 81, 16))
        self.label_11.setObjectName("label_11")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(500, 30, 121, 16))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(130, 30, 61, 16))
        self.label_2.setObjectName("label_2")
        self.cmpCodigo = QtWidgets.QLineEdit(Dialog)
        self.cmpCodigo.setGeometry(QtCore.QRect(30, 50, 51, 20))
        self.cmpCodigo.setObjectName("cmpCodigo")
        self.pushBtnCancelar = QtWidgets.QPushButton(Dialog)
        self.pushBtnCancelar.setGeometry(QtCore.QRect(130, 410, 75, 23))
        self.pushBtnCancelar.setObjectName("pushBtnCancelar")
        self.cmpPesoBruto = QtWidgets.QLineEdit(Dialog)
        self.cmpPesoBruto.setGeometry(QtCore.QRect(30, 240, 121, 20))
        self.cmpPesoBruto.setObjectName("cmpPesoBruto")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(30, 330, 51, 16))
        self.label_20.setObjectName("label_20")
        self.pushBtnSalvar = QtWidgets.QPushButton(Dialog)
        self.pushBtnSalvar.setGeometry(QtCore.QRect(40, 410, 75, 23))
        self.pushBtnSalvar.setObjectName("pushBtnSalvar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Cód. de Barra"))
        self.label_22.setText(_translate("Dialog", "Alternativo"))
        self.label_6.setText(_translate("Dialog", "Cód. Patrimônio"))
        self.toolCodForn.setText(_translate("Dialog", "..."))
        self.toolCodProd.setText(_translate("Dialog", "..."))
        self.label_12.setText(_translate("Dialog", "Fator Venda"))
        self.label_7.setText(_translate("Dialog", "NCM/SH"))
        self.label_18.setText(_translate("Dialog", "Descrição Fornecedor"))
        self.label_14.setText(_translate("Dialog", "Peso Bruto"))
        self.label_17.setText(_translate("Dialog", "Comprimento"))
        self.label_10.setText(_translate("Dialog", "Fator Entrada"))
        self.label_9.setText(_translate("Dialog", "Fator Fornecedor"))
        self.label_23.setText(_translate("Dialog", "Classif. ABC"))
        self.label_15.setText(_translate("Dialog", "Largura"))
        self.label_21.setText(_translate("Dialog", "Descrição Fornecedor Alternativo"))
        self.label.setText(_translate("Dialog", "Código"))
        self.label_8.setText(_translate("Dialog", "Unid. Forn."))
        self.label_5.setText(_translate("Dialog", "Dun-14"))
        self.label_16.setText(_translate("Dialog", "Altura"))
        self.label_19.setText(_translate("Dialog", "Cód. Forn"))
        self.pushBtnLimpar.setText(_translate("Dialog", "Limpar"))
        self.label_13.setText(_translate("Dialog", "Unid. Venda"))
        self.toolCodFornAlternativo.setText(_translate("Dialog", "..."))
        self.label_11.setText(_translate("Dialog", "Unid. Ent."))
        self.label_3.setText(_translate("Dialog", "Descrição Reduzida"))
        self.label_2.setText(_translate("Dialog", "Descrição"))
        self.pushBtnCancelar.setText(_translate("Dialog", "Cancelar"))
        self.label_20.setText(_translate("Dialog", "Cód. Forn"))
        self.pushBtnSalvar.setText(_translate("Dialog", "Salvar"))

